services:
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    command: daemon --docker
    networks:
      - ofelia_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia-job-executions:/ofelia-job-executions
      - ./.restic_pass:/.restic_pass:ro
    labels:
      ofelia.save-folder: "/ofelia-job-executions"
      ofelia.job-exec.vaultwarden-db-backup-creation.schedule: "@daily"
      ofelia.job-exec.vaultwarden-db-backup-creation.container: "vaultwarden"
      ofelia.job-exec.vaultwarden-db-backup-creation.command: "/vaultwarden backup"
      ofelia.job-exec.vaultwarden-db-backup-cleanup.schedule: "@daily"
      ofelia.job-exec.vaultwarden-db-backup-cleanup.container: "vaultwarden"
      ofelia.job-exec.vaultwarden-db-backup-cleanup.command: "find /data -regextype posix-extended -type f -regex '.*db_[0-9]{8}_000000.sqlite3.*' | sort -n | head -n -1 | xargs -r rm -f"
      ofelia.job-exec.backup-integrity-immich.schedule: "@daily"
      ofelia.job-exec.backup-integrity-immich.container: "ofelia"
      ofelia.job-exec.backup-integrity-immich.command: "restic check --read-data-subset '10%' -r "http://${RESTIC_REPOSITORY_BASE}/immich-data"

networks:
  ofelia_net:
    driver: bridge
    name: "ofelia_net"

