services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    ports:
      - '7575:7575'
    networks:
      - caddy_public

networks:
  caddy_public:
    driver: bridge
    name: "caddy_public"