#!/usr/bin/env bash

set -e;


if [ -n "${N8N_POSTGRES_USER:-}" ] && [ -n "${N8N_POSTGRES_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
                CREATE DATABASE ${N8N_POSTGRES_DB};
		CREATE USER ${N8N_POSTGRES_USER} WITH PASSWORD '${N8N_POSTGRES_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${N8N_POSTGRES_DB} TO ${N8N_POSTGRES_USER};
		ALTER DATABASE ${N8N_POSTGRES_DB} OWNER TO ${N8N_POSTGRES_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi

if [ -n "${MB_POSTGRES_USER:-}" ] && [ -n "${MB_POSTGRES_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
                CREATE DATABASE ${MB_POSTGRES_DB};
		CREATE USER ${MB_POSTGRES_USER} WITH PASSWORD '${MB_POSTGRES_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${MB_POSTGRES_DB} TO ${MB_POSTGRES_USER};
		ALTER DATABASE ${MB_POSTGRES_DB} OWNER TO ${MB_POSTGRES_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi
